/*
 * API - ActivateGroup Service
 * Dokumentacja usługi do zarządzania grupami.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package client_restTemplate.io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GroupMember
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-10T15:44:41.159+02:00")
public class GroupMember {
  @JsonProperty("accountId")
  private String accountId = null;

  @JsonProperty("msisdn")
  private String msisdn = null;

  @JsonProperty("partyId")
  private String partyId = null;

  /**
   * Status abonenta w grupie
   */
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    ACTIVATION_IN_PROGRESS("ACTIVATION_IN_PROGRESS"),
    
    DEACTIVATION_IN_PROGRESS("DEACTIVATION_IN_PROGRESS");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  public GroupMember accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Ccbs account id membera grupy
   * @return accountId
  **/
  @ApiModelProperty(value = "Ccbs account id membera grupy")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public GroupMember msisdn(String msisdn) {
    this.msisdn = msisdn;
    return this;
  }

   /**
   * Get msisdn
   * @return msisdn
  **/
  @ApiModelProperty(value = "")
  public String getMsisdn() {
    return msisdn;
  }

  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }

  public GroupMember partyId(String partyId) {
    this.partyId = partyId;
    return this;
  }

   /**
   * Party id membera
   * @return partyId
  **/
  @ApiModelProperty(value = "Party id membera")
  public String getPartyId() {
    return partyId;
  }

  public void setPartyId(String partyId) {
    this.partyId = partyId;
  }

  public GroupMember status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status abonenta w grupie
   * @return status
  **/
  @ApiModelProperty(value = "Status abonenta w grupie")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupMember groupMember = (GroupMember) o;
    return Objects.equals(this.accountId, groupMember.accountId) &&
        Objects.equals(this.msisdn, groupMember.msisdn) &&
        Objects.equals(this.partyId, groupMember.partyId) &&
        Objects.equals(this.status, groupMember.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, msisdn, partyId, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupMember {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    msisdn: ").append(toIndentedString(msisdn)).append("\n");
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

