/*
 * API - ActivateGroup Service
 * Dokumentacja usługi do zarządzania grupami.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package client_restTemplate.io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Group
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-10T15:44:41.159+02:00")
public class Group {
  @JsonProperty("groupCode")
  private String groupCode = null;

  @JsonProperty("members")
  private List<GroupMember> members = null;

  @JsonProperty("ownerMsisdn")
  private String ownerMsisdn = null;

  /**
   * Status ownera grupy
   */
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    ACTIVATION_IN_PROGRESS("ACTIVATION_IN_PROGRESS"),
    
    DEACTIVATION_IN_PROGRESS("DEACTIVATION_IN_PROGRESS");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  public Group groupCode(String groupCode) {
    this.groupCode = groupCode;
    return this;
  }

   /**
   * Kod grupy pobrany z billingu
   * @return groupCode
  **/
  @ApiModelProperty(example = "005", value = "Kod grupy pobrany z billingu")
  public String getGroupCode() {
    return groupCode;
  }

  public void setGroupCode(String groupCode) {
    this.groupCode = groupCode;
  }

  public Group members(List<GroupMember> members) {
    this.members = members;
    return this;
  }

  public Group addMembersItem(GroupMember membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<GroupMember>();
    }
    this.members.add(membersItem);
    return this;
  }

   /**
   * Lista abonentów w grupie
   * @return members
  **/
  @ApiModelProperty(value = "Lista abonentów w grupie")
  public List<GroupMember> getMembers() {
    return members;
  }

  public void setMembers(List<GroupMember> members) {
    this.members = members;
  }

  public Group ownerMsisdn(String ownerMsisdn) {
    this.ownerMsisdn = ownerMsisdn;
    return this;
  }

   /**
   * Numer MSISDN ownera grupy
   * @return ownerMsisdn
  **/
  @ApiModelProperty(value = "Numer MSISDN ownera grupy")
  public String getOwnerMsisdn() {
    return ownerMsisdn;
  }

  public void setOwnerMsisdn(String ownerMsisdn) {
    this.ownerMsisdn = ownerMsisdn;
  }

  public Group status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status ownera grupy
   * @return status
  **/
  @ApiModelProperty(value = "Status ownera grupy")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Group group = (Group) o;
    return Objects.equals(this.groupCode, group.groupCode) &&
        Objects.equals(this.members, group.members) &&
        Objects.equals(this.ownerMsisdn, group.ownerMsisdn) &&
        Objects.equals(this.status, group.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupCode, members, ownerMsisdn, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Group {\n");
    
    sb.append("    groupCode: ").append(toIndentedString(groupCode)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    ownerMsisdn: ").append(toIndentedString(ownerMsisdn)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

