/*
 * API - ActivateGroup Service
 * Dokumentacja usługi do zarządzania grupami.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package client_restTemplate.io.swagger.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * GroupResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-10T15:44:41.159+02:00")
public class GroupResponse {
  @JsonProperty("group")
  private Group group = null;

  @JsonProperty("orderId")
  private Long orderId = null;

  public GroupResponse group(Group group) {
    this.group = group;
    return this;
  }

   /**
   * Struktura dodanej/modyfikowanej grupy
   * @return group
  **/
  @ApiModelProperty(value = "Struktura dodanej/modyfikowanej grupy")
  public Group getGroup() {
    return group;
  }

  public void setGroup(Group group) {
    this.group = group;
  }

  public GroupResponse orderId(Long orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Numer orderu z CRMD
   * @return orderId
  **/
  @ApiModelProperty(value = "Numer orderu z CRMD")
  public Long getOrderId() {
    return orderId;
  }

  public void setOrderId(Long orderId) {
    this.orderId = orderId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupResponse groupResponse = (GroupResponse) o;
    return Objects.equals(this.group, groupResponse.group) &&
        Objects.equals(this.orderId, groupResponse.orderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(group, orderId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupResponse {\n");
    
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

